; SPDX-FileCopyrightText: 2023 Andreas Sig Rosvall
;
; SPDX-License-Identifier: GPL-3.0-or-later

LED_GREEN      = P0.0
LED_GREEN_PORT = 0
LED_GREEN_PIN  = 0

USB_DPLUS      = P1.0
USB_DPLUS_PORT = 1
USB_DPLUS_PIN  = 0

LED_RED        = P1.1
LED_RED_PORT   = 1
LED_RED_PIN    = 1

BTN0           = P1.2
BTN0_PORT      = 1
BTN0_PIN       = 2

BTN1           = P1.3
BTN1_PORT      = 1
BTN1_PIN       = 3

UART_TX        = P1.6
UART_TX_PORT   = 1
UART_TX_PIN    = 6

UART_RX        = P1.7
UART_RX_PORT   = 1
UART_RX_PIN    = 7
